name: Deploy Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/proyecto/VlsmCalculator/
          git pull origin main
          git status
          docker stop vlsmcalculator
          docker rm vlsmcalculator
          docker build -t vlsmcalculator-image .
          docker run -dit -p 5018:80 --restart unless-stopped --name vlsmcalculator vlsmcalculator-image 
